/**
 * PDF Export Utility
 *
 * Generates branded Parrish HALO PDF reports using jsPDF + autoTable.
 * Includes header with brand color band, title, date range, summary
 * statistics, the data table, and a page-numbered footer watermark.
 *
 * @module utils/exportPdf
 */

import jsPDF from 'jspdf';
import autoTable, { RowInput } from 'jspdf-autotable';

// Parrish HALO palette (from index.css). RGB tuples for jsPDF.
const BRAND = {
  primary: [30, 158, 73] as [number, number, number],   // primary-500
  navy: [13, 82, 157] as [number, number, number],       // navy-500
  ink: [17, 24, 39] as [number, number, number],         // gray-900
  muted: [107, 114, 128] as [number, number, number],    // gray-500
  rule: [229, 231, 235] as [number, number, number],     // gray-200
  bandBg: [232, 245, 238] as [number, number, number],   // primary-50
};

export interface PdfReportSummaryItem {
  label: string;
  value: string;
}

export interface PdfReportConfig {
  title: string;
  subtitle?: string;
  /** Range covered by the report (e.g., "Jan 1 – Apr 28, 2026") */
  dateRange?: string;
  summary?: PdfReportSummaryItem[];
  headers: string[];
  rows: RowInput[];
  filename: string;
}

const drawHeader = (doc: jsPDF, config: PdfReportConfig): number => {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Top brand band
  doc.setFillColor(...BRAND.bandBg);
  doc.rect(0, 0, pageWidth, 22, 'F');
  doc.setFillColor(...BRAND.primary);
  doc.rect(0, 22, pageWidth, 1.5, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...BRAND.navy);
  doc.text('Parrish HALO', 14, 11);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.muted);
  doc.text('Parrish Health Systems · Compliance & Training', 14, 17);

  // Generated timestamp (top right)
  const generated = new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: 'numeric', minute: '2-digit',
  });
  doc.text(`Generated ${generated}`, pageWidth - 14, 11, { align: 'right' });

  // Report title
  let cursorY = 34;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...BRAND.ink);
  doc.text(config.title, 14, cursorY);
  cursorY += 6;

  if (config.subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.muted);
    doc.text(config.subtitle, 14, cursorY);
    cursorY += 5;
  }

  if (config.dateRange) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.muted);
    doc.text(`Date range: ${config.dateRange}`, 14, cursorY);
    cursorY += 4;
  }

  // Summary stats
  if (config.summary && config.summary.length > 0) {
    cursorY += 4;
    doc.setDrawColor(...BRAND.rule);
    doc.setLineWidth(0.2);
    doc.line(14, cursorY, pageWidth - 14, cursorY);
    cursorY += 5;

    const colWidth = (pageWidth - 28) / config.summary.length;
    config.summary.forEach((item, idx) => {
      const x = 14 + idx * colWidth;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...BRAND.muted);
      doc.text(item.label.toUpperCase(), x, cursorY);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(...BRAND.ink);
      doc.text(item.value, x, cursorY + 6);
    });
    cursorY += 12;
  }

  return cursorY + 4;
};

const drawFooter = (doc: jsPDF) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BRAND.rule);
    doc.setLineWidth(0.2);
    doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.muted);
    doc.text('Generated by Parrish HALO', 14, pageHeight - 7);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - 14,
      pageHeight - 7,
      { align: 'right' }
    );
  }
};

export function exportToPdf(config: PdfReportConfig): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' });
  const startY = drawHeader(doc, config);

  autoTable(doc, {
    startY,
    head: [config.headers],
    body: config.rows,
    theme: 'grid',
    headStyles: {
      fillColor: BRAND.navy,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
      halign: 'left',
    },
    bodyStyles: {
      fontSize: 8.5,
      textColor: BRAND.ink,
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    styles: {
      cellPadding: 2,
      lineColor: BRAND.rule,
      lineWidth: 0.1,
    },
    margin: { left: 14, right: 14, bottom: 16 },
    didDrawPage: (data) => {
      // Re-draw the header on subsequent pages.
      if (data.pageNumber > 1) {
        drawHeader(doc, config);
      }
    },
  });

  drawFooter(doc);

  const filename = config.filename.endsWith('.pdf') ? config.filename : `${config.filename}.pdf`;
  doc.save(filename);
}
